export enum ErrorWebEnum {
    INVALID_JWT_SIGNATURE = "INVALID_JWT_SIGNATURE",
    INVALID_JWT_TOKEN = "INVALID_JWT_TOKEN",
    EXPIRED_JWT_TOKEN ="EXPIRED_JWT_TOKEN",
    UNSUPPORT_JWT_TOKEN ="UNSUPPORT_JWT_TOKEN",
    JWT_CLAIMS_EMPTY = "JWT_CLAIMS_EMPTY"
}